name: JoinWelcome
version: ${project.version}
main: cn.bdcraft.joinwelcome.Main
api-version: 1.16
authors: [happyvalley]
description: Send welcome message when player join server
website: www.bdcraft.cn

commands:
  joinwelcome:
    description: JoinWelcome plugin help menu
    usage: /joinwelcome
    permission: joinwelcome.general

permissions:
  joinwelcome.general:
    description: Main permission for User
    default: true